### ISSUE TITLE
MBAutoCompleteTextField does not escape regex

### ISSUE THREAD

**Issue by sihaack** [simonziegler/BlazorMdc#1039]
**Describe the bug**
The method BuildSelectList does not escape the fieldText argument which can throw a exception if invalid regex is entered.

**To Reproduce**
1. Enter any string containing "???" into the input box.

**Expected behavior**
Escaping the user input used in any regex pattern.

**Environment**
 - dotnet version: .net7.0
 - Browser with version: Microsoft Edge
 - Version of Material.Blazor: 4.0.0-preview20

**Additional context**
The component is used with the oninput event which validates the input each time it's called.

**Comment by simonziegler** [comment]
Thanks for posting this @sihaack. I'm a bit behind in looking into this and will do so as soon as I can.

**Comment by simonziegler** [comment]
@sihaack, after a long, long wait I've finally found time to address this issue. All three autocompletes will be escaped in the next release in the coming few days.
