### ISSUE TITLE
https://material-blazor.com failing to load - giving "An unhandled error has occurred. Reload X"

### ISSUE THREAD

**Issue by darpanp** [simonziegler/BlazorMdc#1071]
**Describe the bug**
Entered the following in the URL bar - https://material-blazor.com. I have also tried directly clicking the link from Github. It has been giving me "An unhandled error has occurred. Reload X" error. I used to be able to get to this website before. I have tried this with latest version of Chrome and Microsoft Edge. In Chrome, I inspected the developer's toolbar (F12) and see failed to load resources message in the console. Looks like the resources are being loaded with this URL.
Examples:
https://material-blazor.com/Material.Blazor/_content/Material.Blazor.Website/css/material-default-theme.min.css
https://material-blazor.com/Material.Blazor/_framework/blazor.webassembly.js
https://material-blazor.com/Material.Blazor/_content/Material.Blazor/material.blazor.min.js

**To Reproduce**
1. Go to 'https://material-blazor.com'
2. Receive an "An unhandled error has occurred. Reload X". Screenshots below.

**Expected behavior**
Expecting the website to load the resources correctly.

**Screenshots**
![DevToolbar-Error](https://github.com/Material-Blazor/Material.Blazor/assets/237623/03c14ea2-9cf9-4494-b55f-4ed01b40700f)
![WebsiteLoadingError](https://github.com/Material-Blazor/Material.Blazor/assets/237623/622da586-c893-4432-8b23-48b53c01cc93)

**Environment**
 - Browser with version: Chrome: Version 116.0.5845.141 (Official Build) (64-bit)

**Additional context**
As per example, I tried loading material.blazor.min.js by removing the first instance of Material.Blazor in the resource link and that seems to find/load the files correctly.

**Comment by MarkStega** [comment]
This is a known problem and will be resolved when we release 5,0 RC1

In the meantime you can browse the current release at https://material-blazor.github.io/Material.Blazor.Current/

and the MD3 preview at https://material-blazor.github.io/Material.Blazor.MD3.Current/

Sorry for any inconvenience...

**Comment by MarkStega** [comment]
Closed as "resolved in RC1"
