### ISSUE TITLE
Theme switcher on demo website seems to throw Exception

### ISSUE THREAD

**Issue by DanBiscotti** [simonziegler/BlazorMdc#1163]
**Describe the bug**
I am checking out the demo website and trying to switch the theme in the top right corner, but instead the pop up down the bottom appears saying that "An unhandled error has occurred."

**To Reproduce**
1. Go to https://material-blazor.com/
2. Click on three dots top right and select different theme

**Expected behavior**
Theme to be switched

**Comment by MarkStega** [comment]
Repaired in 5.0.1
