### ISSUE TITLE
What is the purpose of content remove, content include in csproj?

### ISSUE THREAD

**Issue by pingu2k4** [simonziegler/BlazorMdc#1225]
Hey,

Just a curiosity more than anything. What is achieved by removing and then including the js / css files in the csproj? 

EG:
```xml
<!--Keep this Remove/Include pair-->
<Content Remove="@(OutputStaticAssetsScripts)" />
<Content Include="@(OutputStaticAssetsScripts)" />
```

What does this do for us?

**Comment by MarkStega** [comment]
@pingu2k4 
The remove/include was a "magic incantation" supplied by @javiercn; The issue being solved was that generated resources (js/css) were not being bundled in the published package.

This inclusion goes back to https://github.com/dotnet/aspnetcore/issues/35274

**Comment by pingu2k4** [comment]
Thanks so much for the link and explanation :D
