### ISSUE TITLE
Use Material.Blazor and MaterialBlazor.MD3 simultaneously in a project

### ISSUE THREAD

**Issue by saadsaeed01** [simonziegler/BlazorMdc#1245]
Hello

How can I use Material 3 NuGet alongside Material 2 NuGet?

The problem is components Navigation Drawer, App bar and many other components are not ported yet in Material 3 NuGet. I was thinking of using both of the NuGet packages simultaneously but this is causing conflicts in name spaces

**Comment by MarkStega** [comment]
There is a way of combining the implementations demonstrated by the MD3 website (which uses both MD2 & MD3 components).

Until recently it even used the MD2 navigation drawer and menuitems.

What was done in this project was to copy the needed MD2 components into a separate directory and then change all of the Material.Blazor namespace declarations. You could use the MD3 nuget package and copy all of the needed MD2 components to your project changing their namespace to M.B.MD2.

If that is too much work I could either
(1) change the MD3 namespace from M.B to M.B.MD3 and then deploy it on the next Microsoft patch Tuesday
(2) add whatever MD2 components that you need  into the MD3 project (if it is a modest list of components)

**Comment by MarkStega** [comment]
Material.Blazor.MD3 has been deprecated due to the abandonment of MWC3 by Google

**Comment by serega404** [comment]
> Material.Blazor.MD3 has been deprecated due to the abandonment of MWC3 by Google

Please write about it in the readme, I've spent a lot of time trying to figure out what's going on.

**Comment by MarkStega** [comment]
Here is the announcement in June:

```
Hi everyone, we have an important update for the community.

Material Design is focusing on support for Google's large-scale internal Wiz framework, and has reassigned the engineers working on Material Web Components. This places MWC into maintenance mode.

MWC is not deprecated or going away, but Material Design is no longer actively staffing its development.

What does this mean?

New features and components are no longer planned.
GitHub PRs will not be accepted by default. Small PRs may be reviewed on a case-by-case basis.
Ongoing support will require volunteer time from the team.
We are investigating ways to continue development of new features and components, including identifying new maintainers. We'll post updates here as we learn more.

Thank you,

Elizabeth, on behalf of the Material Web team
