### ISSUE TITLE
404 in wasm  asp.net hosted

### ISSUE THREAD

**Issue by SalimiHabib** [simonziegler/BlazorMdc#563]
Test with default WASM  template of visual studio 2019
using  `<PackageReference Include="Material.Blazor" Version="2.0.0-preview.6" />`
in  asp.net hosted client project result to 404 
project define as    `<TargetFramework>net5.0</TargetFramework>`
Index file header include 
    `<link href="_content/Material.Blazor/material.blazor.min.css" rel="stylesheet" />`
     `<link href="_content/Material.Blazor/material-components-web.min.css" rel="stylesheet" />`
in client project we have 
`builder.Services.AddMBServices()`  

and in server project we have 
` app.UseStaticFiles();  `
`webBuilder.UseStaticWebAssets(); `

**Comment by MarkStega** [comment]
You can't use a .Net 6 project (ie, Material.Blazor) in a .Net 5 project (yours).

You need to upgrade your project to .Net 6 / VS 2022 or use version 1 of M.B
