### ISSUE TITLE
Tooltip does not disappear

### ISSUE THREAD

**Issue by truthz03** [simonziegler/BlazorMdc#582]
Hi,

is this a known bug that tooltips does not disappear?
If I move the cursor to the component the tooltip gets shown but never moves away.

I have tested with Edge and Chrome, with a MBIconButton inside my own app and on [your tooltip demo page](https://material-blazor.com/tooltip)

I'm using the Material.Blazor 2.0.0 Nuget

Thanks

**Comment by MarkStega** [comment]
I'm confirming that what you are seeing is indeed a bug; I just pinged Simon since he implemented the tooltips.

**Comment by simonziegler** [comment]
Thanks for this @truthz03. We're releasing 2.0.1 fixing both this and a bug in MBPaginator today.
