### ISSUE TITLE
Installation instructions unclear when starting from blazor template project

### ISSUE THREAD

**Issue by jpmikkers** [simonziegler/BlazorMdc#599]
**Describe the bug**
Installation instructions unclear/wrong when starting from blazor server template project. E.g.:
- there is no `<head>` or `<body>` in `_Host.cshtml` , those are in `_Layout.cshtml`
- also, what should be done with the existing links to `bootstrap.min.css` ?
- In the instructions for `AddMBServices()` there are calls to `Utilities.GetDefault*Configuration`. Utilities does not seem to exist in version 2.1.0

**To Reproduce**
1. in vs2022 create a new blazor server project (.net 6.0)
2. follow material.blazor installation instructions using material.blazor nuget package version 2.1.0

**Comment by MarkStega** [comment]
I've updated the documentation and it will appear in 2.2.1;

You found the proper location for the anchor. I don't know why they did this change, it seems to just obscure the implementation.

I'd like to be stronger and say 'take out the reference to bootstrap.min.css' but the sample uses it. Once you have everything in Material you can remove it...

The AddMBServices should just be "AddMbServices();" with optional configuration sections.
