### ISSUE TITLE
MB breaks with dotnet7

### ISSUE THREAD

**Issue by Johan-allegiance** [simonziegler/BlazorMdc#798]
All of my material blazor components break when I update to dotnet 7. Can you tell me why is this happening?
![Screenshot 2023-01-26 095146](https://user-images.githubusercontent.com/68000053/214783514-12ad0ba2-f875-448f-bc3e-e2478d42f89b.png)

**Comment by MarkStega** [comment]
I ran a project during the year that .Net 7 was in development with no issues using Material.Blazor 3.x which is .Net 6.0

It looks more like you are missing some javascript in that the errors are missing 'Material.Blazor.  Post you index.html if you need assistance.

**Comment by Johan-allegiance** [comment]
We were running this application on dotnet 6 for the last couple of months with no issues. The moment we updated our application to dotnet 7, all off material started breaking. The dropdown/selects and the numeric number fields broke.

**Comment by simonziegler** [comment]
@Johan-allegiance sorry I didn't note your issue sooner. @MarkStega and I both consume MB with .NET 7. As Mark says, that console exception shows that some javascript hasn't been found. `MaterialBlazor.MBTextField.setType` is a function that enables numeric fields to switch an `<input .../>` element from `type="text"` to `type="number"` as you focus in and back again.

Can you please post where you include `material.blazor.min.js` in your index.html file (you seem to be on WASM). Also which version of Material.Blazor are you using?

Last question: I'm super curious what you're using Material.Blazor for. Can you share some info?

**Comment by simonziegler** [comment]
@Johan-allegiance I could spare 20 mins for a screen sharing session if that would help.

**Comment by Johan-allegiance** [comment]
Hi @simonziegler Apologies for the delayed response. It was in fact a javascript issue. When we updated to .net7, we also updated material, but I never changed the script file in the index.html. So it is sorted thank you.

**Comment by simonziegler** [comment]
Great to hear. I'll close the issue. I would be fascinated to know what you're using MB for? We don't have a community so don't really get any feedback.
